export const artistsData = [
  {
    id: 1,
    name: "Shreya Ghoshal",
    category: "Singer",
    bio: "Legendary playback singer with over 20 years in the industry, known for her melodious voice across Bollywood, regional cinema, and classical music. Winner of 4 National Film Awards and multiple Filmfare Awards, specializing in romantic ballads and classical renditions.",
    location: "Mumbai, Maharashtra",
    priceRange: "₹1500000+",
    rating: 5,
    reviews: 342,
    languages: ["Hindi", "Bengali", "Tamil", "Telugu", "Malayalam", "Marathi"],
    image: "https://tds-images.thedailystar.net/sites/default/files/styles/very_big_201/public/images/2024/09/24/shreya_ghoshal.jpg",
  },
  {
    id: 2,
    name: "Vipul Goyal",
    category: "Comedian",
    location: "Mumbai, Maharashtra",
    priceRange: "₹1000000-1500000",
    rating: 5,
    image: "https://yt3.googleusercontent.com/ytc/AIdro_n1pxm3eQrHAsQwnJDBJu8-FEFnWUrmffTqMEfIM4y6yA=s900-c-k-c0x00ffffff-no-rj",
    specialty: "Stand-up Comedian",
    awards: "Popular Comedy Creator",
    bio: "Vipul Goyal is one of India's most beloved stand-up comedians, known for his relatable humor and impeccable timing. With millions of YouTube views and sold-out shows across the country, he brings laughter through his observational comedy about everyday life, relationships, and modern society."
  },
  {
    id: 3,
    name: "Arijit Singh",
    category: "Singer",
    location: "Jiaganj, West Bengal",
    priceRange: "₹1500000+",
    rating: 5,
    image: "https://lastfm.freetls.fastly.net/i/u/ar0/ad7e05685bef8909f27c0d95bf79425c.jpg",
    specialty: "Playback & Live Performer",
    awards: "Multiple Filmfare Award Winner",
    bio: "Arijit Singh is India's most celebrated playback singer, known for his soulful voice and emotional depth. With numerous Filmfare Awards and chart-topping hits, he has become the voice of contemporary Bollywood romance and continues to mesmerize audiences with his live performances."
  },
  {
    id: 4,
    name: "DJ Chetas",
    category: "DJ",
    bio: "India's most popular Bollywood DJ and music producer, known for his chart-topping remixes and electrifying live performances. Regular performer at major music festivals and celebrity events across the country.",
    location: "Mumbai, Maharashtra",
    priceRange: "₹200000-500000",
    rating: 4.8,
    reviews: 198,
    languages: ["Hindi", "English", "Gujarati"],
    image: "https://res.cloudinary.com/https-highape-com/image/upload/q_auto:low,f_auto/v1524823603/xnplksompb8ksfefesgb.jpg",
  },
  {
    id: 5,
    name: "Kathak Kendra Sharmila Sharma",
    category: "Dancer",
    bio: "Renowned Kathak dancer and choreographer, disciple of Pandit Birju Maharaj. Padma Shri awardee with over 30 years of experience in classical Indian dance, known for her graceful performances and innovative choreography.",
    location: "Delhi, NCR",
    priceRange: "₹500000-1000000",
    rating: 4.9,
    reviews: 167,
    languages: ["Hindi", "English", "Urdu"],
    image: "https://www.indiandanceandmusicdirectory.com/wp-content/uploads/2020/12/DSC0005-3.jpg",
  },
  {
    id: 6,
    name: "Eshani Sathe",
    category: "Dancer",
    bio: "An incredibly talented Kathak dancer who is weaving her art into a language that you can understand.",
    location: "Delhi, NCR",
    priceRange: "₹500000-1000000",
    rating: 4.9,
    reviews: 167,
    languages: ["Hindi", "English", "Urdu"],
    image: "https://images.squarespace-cdn.com/content/v1/5aef39aab27e390f37df214e/1581919220659-C9IL17H06KGC8URAFZQ2/Eshani+%2B+Tanveer+02.jpeg?format=1000w",
  },
  {
    id: 7,
    name: "Gaur Gopal Das (Memorial Speaker)",
    category: "Speaker",
    bio: "An Indian monk, motivational speaker, and former electrical engineer. He is a member of the International Society for Krishna Consciousness.",
    location: "Delhi, NCR",
    priceRange: "N/A",
    rating: 4.7,
    reviews: 285,
    languages: ["English", "Hindi", "Tamil"],
    image: "https://i1.sndcdn.com/artworks-000149134564-gtcs7v-t500x500.jpg",
  },
  {
    id: 8,
    name: "Sandeep Maheshwari",
    category: "Speaker",
    bio: "Sandeep Maheshwari is a name among millions who struggled, failed & surged ahead in pursuit of success. Rowing through ups and downs, it was time that taught him the true meaning of his life.",
    location: "Delhi, NCR",
    priceRange: "500000-1000000",
    rating: 4.7,
    reviews: 285,
    languages: ["English", "Hindi"],
    image: "https://pearlentertainment.in/wp-content/uploads/2024/08/656fa7dd8d09a0b051c5d364d7e5765f.jpg",
  },
  {
    id: 9,
    name: "Kailash Kher",
    category: "Singer",
    bio: "Sufi rock singer and music composer famous for hits like 'Allah Ke Bande' and 'Arziyan'. Known for his powerful voice and spiritual performances that blend Indian classical music with contemporary sounds.",
    location: "Mumbai, Maharashtra",
    priceRange: "₹1000000-1500000",
    rating: 4.8,
    reviews: 203,
    languages: ["Hindi", "Punjabi", "Urdu", "English"],
    image: "https://www.ritzmagazine.in/wp-content/uploads/2017/03/kailash-kher.jpg",
  },
  {
    id: 10,
    name: "Nucleya",
    category: "DJ",
    bio: "Pioneer of Indian electronic music and bass music culture. Known for incorporating traditional Indian sounds with modern electronic beats. Regular headliner at major music festivals like Sunburn and NH7 Weekender.",
    location: "Mumbai, Maharashtra",
    priceRange: "₹200000-500000",
    rating: 4.6,
    reviews: 156,
    languages: ["English", "Hindi"],
    image: "https://images.hindustantimes.com/rf/image_size_800x600/HT/p2/2016/10/13/Pictures/_24747528-9155-11e6-957d-83f787ac5cdf.jpg",
  },
  {
    id: 11,
    name: "Terrence Lewis",
    category: "Dancer",
    bio: "Celebrity choreographer and contemporary dance expert, known from reality shows like 'So You Think Can Dance' and 'Dance India Dance'. Founder of Terrence Lewis Contemporary Dance Company with innovative fusion choreography.",
    location: "Mumbai, Maharashtra",
    priceRange: "₹200000-500000",
    rating: 4.9,
    reviews: 189,
    languages: ["English", "Hindi", "Marathi"],
    image: "https://m.media-amazon.com/images/M/MV5BY2I0MDhhYjAtMWU1Zi00NGI0LTg3MDEtNmNmYWM5MTA4OGE3XkEyXkFqcGc@._V1_.jpg",
  },
  {
    id: 12,
    name: "Kapil Sharma",
    category: "Comedian",
    bio: "an Indian stand-up comedian, television host, actor, dubbing artist, producer and singer.",
    location: "Mumbai, Maharashtra",
    priceRange: "₹1000000-1500000",
    rating: 4.8,
    reviews: 152,
    languages: ["English", "Hindi", "Gujarati"],
    image: "https://d3mbwbgtcl4x70.cloudfront.net/Kapil_Sharma_8334ee5d31.webp",
  },
  {
    id: 13,
    name: "Shakti Mohan",
    category: "Dancer",
    bio: "A versatile dancer and choreographer, Shakti Mohan rose to fame as the winner of 'Dance India Dance Season 2'. Known for her contemporary dance style and powerful performances, she has choreographed for Bollywood films and television shows.",
    location: "Mumbai, Maharashtra",
    priceRange: "₹500000-1000000",
    rating: 4.7,
    reviews: 210,
    languages: ["English", "Hindi", "Marathi"],
    image: "https://i.pinimg.com/736x/67/19/bb/6719bbf92565cbea01fcfe817bb9b9ae.jpg",
  },
];


export const artistSubmissions = [
  {
    id: 1,
    name: "Armaan Malik",
    category: "Singer",
    location: "Mumbai, Maharashtra",
    feeRange: "₹3,00,000-6,00,000",
    status: "pending",
    submittedDate: "2024-01-15",
  },
  {
    id: 2,
    name: "Dhvani Bhanushali",
    category: "Singer",
    location: "Mumbai, Maharashtra",
    feeRange: "₹2,50,000-5,00,000",
    status: "approved",
    submittedDate: "2024-01-14",
  },
  {
    id: 3,
    name: "DJ Aqeel",
    category: "DJ",
    location: "Mumbai, Maharashtra",
    feeRange: "₹1,50,000-3,00,000",
    status: "pending",
    submittedDate: "2024-01-13",
  },
  {
    id: 4,
    name: "Shakti Mohan",
    category: "Dancer",
    location: "Mumbai, Maharashtra",
    feeRange: "₹2,00,000-4,00,000",
    status: "rejected",
    submittedDate: "2024-01-12",
  },
  {
    id: 5,
    name: "Sandeep Maheshwari",
    category: "Speaker",
    location: "Delhi, NCR",
    feeRange: "₹2,00,000-4,00,000",
    status: "approved",
    submittedDate: "2024-01-11",
  },
];

export const bookingRequests = [
  {
    id: 1,
    eventName: "Reliance Annual Conference 2024",
    artistName: "Shreya Ghoshal",
    eventDate: "March 15, 2024",
    budget: "₹8,00,000-12,00,000",
    status: "new",
    clientName: "Reliance Industries",
  },
  {
    id: 2,
    eventName: "Ambani Wedding Celebration",
    artistName: "DJ Chetas",
    eventDate: "April 22, 2024",
    budget: "₹4,00,000-6,00,000",
    status: "responded",
    clientName: "Ambani Family",
  },
  {
    id: 3,
    eventName: "Tata Leadership Summit",
    artistName: "Sandeep Maheshwari",
    eventDate: "February 28, 2024",
    budget: "₹15,00,000-20,00,000",
    status: "new",
    clientName: "Tata Consultancy Services",
  },
];